$agent = <<-'SCRIPT'
echo "hello from server"
apt-get update
apt-get install -y curl
curl -sfL https://get.k3s.io | sh -
until kubectl get nodes > /dev/null 2>&1; do
  sleep 2
done
# Make kubectl usable for vagrant user
mkdir -p /home/vagrant/.kube
cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
chown -R vagrant:vagrant /home/vagrant/.kube
cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
# run the cluster
kubectl apply -f k8s/ 
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define = "csaidiS" do |server|
    server.vm.hostname = "csaidiS"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "512" 
      vb.cpus = 1
    end
    server.vm.network "private_network", ip: 192.168.56.110
    server.vm.provision "shell", inline: $agent
  end

end