apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html

      volumes:
        - name: config
          configMap:
            name: app-1-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3

spec:
  replicas: 1
  selector:
    matchLabels:
      app: third-app

  template:
    metadata:
      labels:
        app: third-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html

      volumes:
        - name: config
          configMap:
            name: app-3-config

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: app2

spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app

  template:
    metadata:
      labels:
        app: second-app

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html

      volumes:
        - name: config
          configMap:
            name: app-2-config
